# Netlify deployment configuration
[build]
  base = "apps/marketing"
  command = "npm run build"
  functions = "netlify/functions"
  publish = "apps/marketing/out"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/dev/null"

# SPA redirects for Next.js static export
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }
