[build]
  base = "apps/marketing"
  command = "npm install && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/download"
  to = "/download/index.html"
  status = 200

[[redirects]]
  from = "/pricing" 
  to = "/pricing/index.html"
  status = 200

[[redirects]]
  from = "/purchase/*"
  to = "/purchase/:splat/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"