// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VoiceInputAssistant.Infrastructure.Data;

#nullable disable

namespace VoiceInputAssistant.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250922015518_InitialCreateSqlite")]
    partial class InitialCreateSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("VoiceInputAssistant.Infrastructure.Data.Entities.ApplicationProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationExecutables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HotkeyConfigs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessNamePatterns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeechRecognitionSettings")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextProcessingRules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowTitlePatterns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationProfiles");
                });

            modelBuilder.Entity("VoiceInputAssistant.Infrastructure.Data.Entities.EngineMetricsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalMetrics")
                        .HasColumnType("TEXT");

                    b.Property<float>("AverageConfidence")
                        .HasColumnType("REAL");

                    b.Property<int>("AverageProcessingTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EngineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<float>("ErrorRate")
                        .HasColumnType("REAL");

                    b.Property<int>("FailedTranscriptions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuccessfulTranscriptions")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTranscriptions")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("EngineName", "Timestamp");

                    b.ToTable("EngineMetrics");
                });

            modelBuilder.Entity("VoiceInputAssistant.Infrastructure.Data.Entities.ErrorEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalData")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationContext")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StackTrace")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("ErrorType", "Timestamp");

                    b.ToTable("ErrorEvents");
                });

            modelBuilder.Entity("VoiceInputAssistant.Infrastructure.Data.Entities.TranscriptionEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<int>("Engine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessedText")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("ApplicationName", "Timestamp");

                    b.ToTable("TranscriptionEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
